aymericbouzy/balise

htdocs/test.php
htdocs/view/layout/application.php

charge un fichier css spécifique à l'action appelée si le fichier existe.

Css per action

---

htdocs/view/layout/application.php

added css file per controller

---

htdocs/view/layout/footer.php

bug report button

---

htdocs/beta/asset/css/user-home.css
htdocs/beta/global/database.php
htdocs/beta/helper/common.php
htdocs/beta/helper/pretty_print.php
htdocs/beta/test.php
htdocs/beta/view/binet/finances.php
htdocs/beta/view/binet/operation/review.php
htdocs/beta/view/home/welcome.php
htdocs/beta/view/layout/flash.php
htdocs/beta/view/layout/footer.php
htdocs/beta/view/layout/header.php
htdocs/beta/view/layout/sidebar.php
htdocs/beta/view/tag/new.php

J'ai fait la plupart corrections de bugs css visibles (cad pas grand chose : il manque show, la page d'accueil): on peut merger sauf si tu veux corriger des bugs ici.

Ui updates

---

htdocs/beta/asset/css/user-home.css
htdocs/beta/controller/binet/admin.php
htdocs/beta/controller/binet/operation.php
htdocs/beta/controller/binet/wave.php
htdocs/beta/controller/operation.php
htdocs/beta/global/before_actions.php
htdocs/beta/global/email.php
htdocs/beta/global/sql.php
htdocs/beta/helper/common.php
htdocs/beta/helper/pretty_print.php
htdocs/beta/index.php
htdocs/beta/model/binet.php
htdocs/beta/model/operation.php
htdocs/beta/test.php
htdocs/beta/view/email/new_admin.php
htdocs/beta/view/email/new_operation.php
htdocs/beta/view/email/new_wave.php
htdocs/beta/view/email/operation_accepted.php
htdocs/beta/view/email/operation_refused.php
htdocs/beta/view/email/operation_rejected.php
htdocs/beta/view/email/operation_validated.php
htdocs/beta/view/email/wave_published.php

WIP
Il me reste à tester un peu, je suis sur qu’il y a des bugs à corriger. Tu peux quand même déjà regarder le texte des emails et la présentation html si tu veux.

Envoi de mails

---

htdocs/.htaccess
htdocs/beta/asset/css/user-home.css
htdocs/beta/controller/binet.php
htdocs/beta/controller/binet/admin.php
htdocs/beta/controller/binet/operation.php
htdocs/beta/controller/binet/wave.php
htdocs/beta/controller/operation.php
htdocs/beta/global/before_actions.php
htdocs/beta/global/constants.php
htdocs/beta/global/email.php
htdocs/beta/global/routes.php
htdocs/beta/global/sql.php
htdocs/beta/helper/common.php
htdocs/beta/helper/form.php
htdocs/beta/helper/pretty_print.php
htdocs/beta/index.php
htdocs/beta/model/binet.php
htdocs/beta/model/operation.php
htdocs/beta/test.php
htdocs/beta/view/email/new_admin.php
htdocs/beta/view/email/new_operation.php
htdocs/beta/view/email/new_wave.php
htdocs/beta/view/email/operation_accepted.php
htdocs/beta/view/email/operation_refused.php
htdocs/beta/view/email/operation_rejected.php
htdocs/beta/view/email/operation_validated.php
htdocs/beta/view/email/wave_published.php

On peut merger
résoud le bug avec link_to (entre autres)

Bug corrections

---

htdocs/beta/Balise.sql
htdocs/beta/config/development.php
htdocs/beta/global/constants.php
htdocs/beta/global/database.php

On peut merger
permet de paramétrer plus simplement la base de donnée dans le fichier de configuration directement

Specific test database

---

.gitignore
htdocs/.htaccess
htdocs/beta/global/routes.php

On peut merger
permet de tomber sur la page d'erreur 400 si on demande une url incompréhensible. Il faut penser à faire /beta/url_rewriting.php

Error document

---

htdocs/beta/view/layout/application.php

correction

---

htdocs/beta/controller/binet.php
htdocs/beta/global/agregation.php
htdocs/beta/helper/common.php
htdocs/beta/helper/pretty_print.php
htdocs/beta/helper/show.php
htdocs/beta/model/term.php
htdocs/beta/view/binet/index.php
htdocs/beta/view/binet/operation/show.php
htdocs/beta/view/binet/show.php

Better php for show binet

---

htdocs/beta/controller/binet/wave.php
htdocs/beta/global/before_actions.php
htdocs/beta/global/common.php
htdocs/beta/global/initialisation.php
htdocs/beta/helper/form.php
htdocs/beta/test.php

C’est fonctionnel, on peut merger.

Date fields in forms

---

htdocs/beta/config/development.php
htdocs/beta/global/constants.php
htdocs/beta/helper/pretty_print.php
htdocs/beta/view/binet/index.php
htdocs/beta/view/home/index.php
htdocs/beta/view/layout/application.php
htdocs/beta/view/layout/sidebar.php
htdocs/beta/view/operation/form.php

On peut merger
Apporte pas mal de corrections de bugs, plusieurs helpers ont été remplis aussi

Bug correction

---

htdocs/beta/controller/binet.php
htdocs/beta/view/binet/show.php

On peut merger
En fait on avait dit qu’on ne pouvait pas retirer les droits subventionneurs d’un binet, sinon ses vagues précédentes n’auraient plus de sens. On peut en rediscuter pour faire quelque chose de plus souple éventuellement.

solves issue

---

htdocs/beta/view/email/new_admin.php

Correction demandée par Nathan

removed link to information in new_admin email

---

htdocs/beta/view/layout/footer.php

On peut merger
C’est pas fou, mais c’est vraiment difficile d’avoir mieux. Pour avoir quelque chose de propre, il faudrait que le BR configure un truc, à mon avis ça vaut pas la peine.

feature implemented

---

htdocs/beta/asset/css/action/show.css
htdocs/beta/asset/css/features/modals.css
htdocs/beta/asset/dist/js/bootstrap.js
htdocs/beta/controller/binet/operation.php
htdocs/beta/helper/pretty_print.php
htdocs/beta/view/binet/budget/show.php
htdocs/beta/view/binet/operation/index.php
htdocs/beta/view/binet/operation/show.php
htdocs/beta/view/layout/application.php

Quelques corrections et l'ajout des liens pour naviguer entre opérations eet budgets.

Linking and correction

---

htdocs/beta/asset/css/common.css
htdocs/beta/asset/css/features/buttons.css
htdocs/beta/asset/css/features/forms.css
htdocs/beta/helper/common.php
htdocs/beta/view/binet/admin/new.php
htdocs/beta/view/binet/change_term.php
htdocs/beta/view/binet/edit.php
htdocs/beta/view/binet/new.php
htdocs/beta/view/layout/application.php
htdocs/beta/view/operation/new.php

Apporte des nouveautés aux inputs des formulaire et change les boutons par défaut de bootstrap.

Forms inputs

---

htdocs/beta/asset/css/common.css
htdocs/beta/asset/css/controller/operation.css
htdocs/beta/asset/css/features/backgrounds.css
htdocs/beta/asset/css/features/buttons.css
htdocs/beta/asset/css/features/panels.css
htdocs/beta/view/binet/operation/review.php
htdocs/beta/view/layout/application.php

On peut merger, on mergera ensuite issue-89 dans master, mais je crois qu'il va y avoir des conflits.

Issue 89 layout

---

htdocs/beta/controller/binet/request.php
htdocs/beta/controller/binet/wave.php
htdocs/beta/helper/form.php
htdocs/beta/model/request.php
htdocs/beta/model/subsidy.php
htdocs/beta/model/wave.php
htdocs/beta/view/binet/request/review.php
htdocs/beta/view/binet/request/show.php
htdocs/beta/view/binet/wave/show.php

je ne sais pas si ça traite midnight issue, je n’arrive pas à la reproduire.

Waves and requests php

---

htdocs/beta/controller/binet/budget.php
htdocs/beta/global/constants.php
htdocs/beta/index.php

On peut merger
résoud le bug qui nous spam depuis hier sur balise.bugreport …
améliore le mail d’erreur

Quelques corrections de bugs et améliorations

---

htdocs/beta/view/binet/operation/show.php

bug bouton delete operation

---

htdocs/beta/controller/binet/operation.php
htdocs/beta/controller/binet/request.php
htdocs/beta/controller/home.php
htdocs/beta/index.php
htdocs/beta/test.php
htdocs/beta/view/binet/wave/show.php
htdocs/beta/view/error/base.php

On peut merger 
* bug quand on supprime une opération qui avait été associée à des budgets par le passé : résolu.
* sécurité de l'étude des demandes de subventions : résolu.
* redirection vers l'accueil si déjà connecté
* bouton de redirection vers le site suite à une erreur : on incite ainsi l'utilisateur à ne pas réitérer l'envoi d'un faux formulaire à cause d'une csrf
* en développement, la page d'erreur 500 ne s'affiche pas.
tout ça en seulement 22 lignes de code ;)

solve bug : error after deleting associated operation

---

htdocs/beta/controller/binet/operation.php
htdocs/beta/controller/operation.php
htdocs/beta/helper/common.php
htdocs/beta/helper/show.php
htdocs/beta/model/budget.php
htdocs/beta/model/request.php
htdocs/beta/test.php
htdocs/beta/view/binet/operation/review.php
htdocs/beta/view/binet/operation/show.php
htdocs/beta/view/binet/validation/index.php
htdocs/beta/view/email/operation_validated.php

On peut merger
Corrige la validation kès

Validation corrections

---

htdocs/beta/controller/binet/base.php
htdocs/beta/controller/binet/request.php
htdocs/beta/controller/binet/wave.php
htdocs/beta/controller/wave.php
htdocs/beta/global/routes.php
htdocs/beta/model/budget.php
htdocs/beta/view/binet/request/show.php
htdocs/beta/view/binet/wave/show.php

On peut merger
Permet de voir une vague et des demandes de subventions d’autres binets, avec seulement les informations que l’on a le droit d’y voir.

Wave public view

---

htdocs/beta/controller/binet/admin.php
htdocs/beta/global/before_actions.php
htdocs/beta/helper/form.php
htdocs/beta/helper/pretty_print.php
htdocs/beta/view/binet/finances.php
htdocs/beta/view/binet/new.php
htdocs/beta/view/binet/request/review.php
htdocs/beta/view/binet/show.php
htdocs/beta/view/binet/wave/show.php
htdocs/beta/view/layout/sidebar.php

complément à la pr précédente

---

htdocs/beta/asset/css/controller/home.css
htdocs/beta/asset/js/jquery.textfill.min.js
htdocs/beta/global/initialisation.php
htdocs/beta/helper/common.php
htdocs/beta/helper/common_js.php
htdocs/beta/view/home/index.php
htdocs/beta/view/layout/application.php

WIP
Corrige juste les problèmes pour les noms de binet longs dans les boutons binets sur l'écran d'accueil.

Index binet buttons

---

htdocs/beta/model/request.php
htdocs/beta/test.php

correction du bug des brouillons
on peut merger.

Bug brouillons

---

htdocs/beta/controller/binet/request.php
htdocs/beta/model/request.php
htdocs/beta/view/binet/request/index.php

on peut merger
ça résout les bugs pour moi.

correction for rough draft

---

htdocs/beta/controller/binet/request.php
htdocs/beta/view/binet/request/edit_form.php
htdocs/beta/view/wave/index.php

On peut merger. Ajoute une modale pour choisir le binet pour lequel on va demander des subventions.
Ajout du nom de la vague dans le formulaire de requête.

Modal choose binet to ask for subsidies

---

htdocs/beta/controller/binet/request.php
htdocs/beta/global/sql.php
htdocs/beta/model/budget.php
htdocs/beta/model/operation.php
htdocs/beta/model/request.php
htdocs/beta/model/term.php
htdocs/beta/test.php
htdocs/beta/view/binet/request/index.php

Request index php

---

htdocs/.htaccess
htdocs/beta/asset/css/common.css
htdocs/beta/asset/css/features/panels.css
htdocs/beta/controller/base.php
htdocs/beta/controller/student.php
htdocs/beta/controller/wave.php
htdocs/beta/global/routes.php
htdocs/beta/helper/pretty_print.php
htdocs/beta/model/binet.php
htdocs/beta/view/home/index.php
htdocs/beta/view/layout/header.php
htdocs/beta/view/layout/sidebar.php
htdocs/beta/view/student/show.php
htdocs/beta/view/wave/index.php

WIP
il reste à faire une jolie view pour le student : je te laisse faire tes commits directement dans cette branche @victornicolet.

Student show

---

htdocs/beta/controller/binet/operation.php
htdocs/beta/model/term.php
htdocs/beta/view/binet/index.php
htdocs/beta/view/layout/sidebar.php

c’est ça que je voulais dire pour le champ state du model term.

a few improvements

---

htdocs/beta/controller/binet.php
htdocs/beta/global/sql.php

la liste des binets est triée par nom des binets.

order by corrected - binets ordered by name

---

htdocs/beta/asset/css/common.css
htdocs/beta/asset/css/features/forms.css
htdocs/beta/helper/form.php
htdocs/beta/view/binet/budget/form.php

Résout le pb du bouton plus, et met à jour le thème des "select-search"

Select search layout

---

htdocs/beta/helper/common.php

La plus petite pull request que je peux faire, mais elle corrige le problème du footer décalé, et ca me permettra de faire mieux niveau mise en page. Il a des trucs que je ne comprenais pas, en fait j'ai oublié de fermer un div et sans la coloration syntaxique c'est chiant à voir.

Forgotten div

---

htdocs/beta/controller/binet/budget.php

On peut merger
Permet de modifier un budget même après que des opérations y ait été associé.

updated budget controller

---

htdocs/beta/view/binet/wave/index.php
htdocs/beta/view/wave/index.php

On peut merger
Le nouveau helper n’était pas utilisé partout.

wave state everywhere

---

htdocs/.htaccess
htdocs/beta/controller/base.php
htdocs/beta/controller/home.php
htdocs/beta/form/bug_report.php
htdocs/beta/global/common.php
htdocs/beta/global/routes.php
htdocs/beta/helper/form.php
htdocs/beta/index.php
htdocs/beta/view/home/bug_report.php
htdocs/beta/view/layout/footer.php

wip 
Permet de faire le rapport de bug directement en ligne, ce qui contourne le problème des personnes n’ayant pas configuré leur client mail.

Bug report in browser

---

htdocs/beta/form/bug_report.php
htdocs/beta/helper/form.php
htdocs/beta/view/home/bug_report.php
htdocs/beta/view/layout/application.php
htdocs/beta/view/layout/footer.php

Le code était correct mais il y avait un bug d'affichage. 
Le fait que le code de la modale soit dans le footer la faisait passer sous la navbar du haut.

Display bug correction

---

htdocs/beta/asset/css/common.css
htdocs/beta/view/layout/footer.php

On peut cliquer au niveau du footer.

Click under the footer

---

htdocs/beta/view/binet/wave/show.php

On peut merger
Corrige un lien dans la liste des demandes de subventions qui nous pourrit la vie.

corrected unpleasant link

---

htdocs/beta/controller/base.php
htdocs/beta/form/bug_report.php

On peut merger
Corrige un petit bug de redirection

Correction de bug de redirection

---

htdocs/beta/controller/base.php
htdocs/beta/view/layout/application.php

On peut merger
Le bug se produisait si on essayait d’accéder au site après avoir été déconnecté au bout d’un certain temps et que l’on demandait une page qui générait une page d’erreur.

Bug corrigé

---

htdocs/beta/asset/css/controller/budget.css
htdocs/beta/controller/binet/budget.php
htdocs/beta/model/wave.php
htdocs/beta/view/binet/budget/index.php

On peut merger
A présent on voit les vagues de subventions apparaitre dans le budget pour les binets subventionneurs.

Waves in budget

---

htdocs/beta/controller/binet/operation.php
htdocs/beta/helper/common.php
htdocs/beta/model/operation.php

On peut merger
On reçoit une notification avec tous les binets subventionneurs concernés quand on ajoute une opération subventionnée à son budget.

Subsidy steps notice

---

htdocs/beta/controller/binet/operation.php
htdocs/beta/view/binet/operation/index.php

On voit les opérations en attente de validation par la kès.

See pending kes validations

---

htdocs/beta/view/help/binet/admin/new.php
htdocs/beta/view/help/binet/budget/index.php
htdocs/beta/view/help/binet/edit.php
htdocs/beta/view/help/binet/operation/index.php
htdocs/beta/view/help/binet/operation/review.php
htdocs/beta/view/help/binet/operation/show.php
htdocs/beta/view/help/binet/request/index.php
htdocs/beta/view/help/binet/show.php
htdocs/beta/view/help/binet/validation.php
htdocs/beta/view/help/home/index.php
htdocs/beta/view/help/student/show.php
htdocs/beta/view/help/wave/index.php
htdocs/beta/view/help/wave/new.php

Il faudra faire encore des modifications du texte, mais ça serait bien de le mettre en ligne pour que l’aide soit partout pour pouvoir sonder les gens sur le texte.

Improvment help text

---

htdocs/beta/view/binet/operation/review_form.php

On peut merger
Corrige le problème de précision du calcul de la somme relevé par alexandre carton

bug d'alexandre carton

---

htdocs/beta/asset/css/action/show.css
htdocs/beta/asset/css/features/panels.css
htdocs/beta/view/binet/request/index.php
htdocs/beta/view/binet/request/review_form.php
htdocs/beta/view/binet/wave/show.php

On peut voir les dates d'envoi des requêtes à quelques endroits

Late requests plus

---

htdocs/beta/controller/binet/budget.php
htdocs/beta/model/budget.php
htdocs/beta/model/request.php
htdocs/beta/model/subsidy.php
htdocs/beta/model/term.php
htdocs/beta/test.php
htdocs/beta/view/binet/budget/index.php
htdocs/beta/view/binet/request/edit_form.php
htdocs/beta/view/binet/request/review_form.php

Permet de voir les subventions disponibles plutôt que les subventions reçues totales.

Subventions disponibles

---

htdocs/beta/view/binet/request/edit_form.php

better php

---

htdocs/beta/asset/css/controller/request.css
htdocs/beta/view/binet/request/edit_form.php

La checkbox n'a pas vriament disparu, mais on voit un switch à la place, cohérent avec l'ancienne checkbox.

Replace checkbox by switch

---

htdocs/beta/view/binet/request/index.php

Corrige les droits dans request index, on ne peut pas voir le montant accordé tant que la requête n'est pas acceptée ou refusée.
Pour les infos dans show je pense qu'on peut attendre. On les a très faiclement dans les différents budgets..

Can see granted amount ?

---

htdocs/beta/view/help/operation/new.php

Opération pour un membre extérieur au binet

---

htdocs/beta/helper/fuzzy_finder.php

On peut merger
Permet de commencer à taper immédiatement dans une barre de recherche quand on charge la page.

added autofocus to search bars

---

htdocs/beta/controller/binet.php
htdocs/beta/form/binet.php
htdocs/beta/view/binet/form.php
htdocs/beta/view/binet/show.php

On peut merger
résout l’issue 205.

Changement de nom de binet

---

htdocs/beta/view/help/binet/request/review.php

Texte aide étude subvention

---

htdocs/beta/view/binet/request/review_form.php

On peut merger. Le montant affiché ne correspondait pas à la légende.

Correction : mauvais montant dans un paneau de review request

---

htdocs/beta/view/help/binet/operation/new.php
htdocs/beta/view/help/binet/operation/review.php

Distinction entre création d'opération et lien budget

---

htdocs/beta/asset/css/common.css
htdocs/beta/helper/pretty_print.php

On peut merger
j’empiète un peu sur ton territoire @victornicolet donc sens-toi libre de refuser, modifier, faire autrement …

Plus joli "s" pour les binets subventionneurs

---

htdocs/beta/asset/css/action/show.css
htdocs/beta/asset/css/common.css
htdocs/beta/helper/common.php
htdocs/beta/view/binet/finances.php
htdocs/beta/view/binet/index.php
htdocs/beta/view/binet/request/edit_form.php
htdocs/beta/view/binet/request/index.php
htdocs/beta/view/binet/validation/index.php
htdocs/beta/view/binet/wave/show.php

On peut merger. Apporte quelques corrections .

Multiple corrections

---

htdocs/.htaccess
htdocs/beta/asset/css/action/index.css
htdocs/beta/asset/css/controller/budget.css
htdocs/beta/asset/css/features/buttons.css
htdocs/beta/asset/css/features/forms.css
htdocs/beta/controller/binet/budget.php
htdocs/beta/form/budget_transfer.php
htdocs/beta/global/before_actions.php
htdocs/beta/global/form.php
htdocs/beta/global/routes.php
htdocs/beta/helper/form.php
htdocs/beta/view/binet/budget/budget_transfer.php
htdocs/beta/view/binet/budget/transfer.php
htdocs/beta/view/binet/budget/transfer_form.php
htdocs/beta/view/binet/finances.php

WIP
Faire le formulaire. Je crois que les balises form sont en trop.

Transfer budgets

---

htdocs/beta/view/binet/wave/show.php

Les corrections de l'issue 218

Corrections

---

htdocs/beta/backup/localhost.sql

Sauvegarde test beta

---

htdocs/config/development.php
htdocs/controller/binet/request.php
htdocs/form/binet.php
htdocs/global/constants.php
htdocs/helper/pretty_print.php
htdocs/view/binet/budget/form.php
htdocs/view/binet/operation/review_form.php
htdocs/view/binet/request/edit_form.php
htdocs/view/layout/application.php

On peut merger
Corrige une foultitude de bugs.
Attention : le fichier de config a été modifié : il faut que vous dupliquer le fichier development.php en l’appelant production.php et en mettant les variables qui vous conviennent.

Corrections de bugs

---

htdocs/Balise.sql

On peut merger
Ajoute le type d’opération rien du tout, et corrige les bugs d’accentuation.

Initialisation de la base de données

---

htdocs/helper/pretty_print.php

On peut merger
corrige le bug relevé par Nathan à 2:48 du matin.

Pas de span dans l'en-tête d'email

---

htdocs/view/help/home/index.php

On peut merger
Un seul caractère modifié …

orthograph correction

---

htdocs/global/before_actions.php

On peut merger
Le site envoie des emails aux webmasters quand une page d’erreur a été générée suite à une navigation normale. 
Désolé pour la PR précédente, j’avais fait de la merde avec git.

added more emails sent to webmaster

---

htdocs/controller/binet/base.php
htdocs/view/binet/wave/index.php

On peut merger
traite l’issue 264

Ouverture des droits de regard de binet/wave/index

---

htdocs/controller/binet/admin.php
htdocs/controller/binet/operation.php
htdocs/global/before_actions.php
htdocs/global/routes.php
htdocs/view/binet/operation/index.php
htdocs/view/home/index.php
htdocs/view/layout/sidebar.php
htdocs/view/tag/new.php

On peut merger
corrige le bug des 24h de la natation.
et remplace des "tags" par "mot-clef"
et corrige des liens vers validation invalides

Noms de binet avec chiffres

---

htdocs/controller/base.php
htdocs/form/bug_report.php
htdocs/global/before_actions.php
htdocs/helper/common.php
htdocs/index.php

On peut merger
Ajoute davantage d’informations aux mails d’erreur, ce qui aide au débuggage.

Ajoute davantage de contexte aux mails d'erreur

---

htdocs/asset/css/common.css
htdocs/view/binet/request/edit_form.php

WIP
J’ai essayé que l’ensemble du rectangle soit cliquable, mais du coup c’est devenu plus moche … Tu peux m’aider @victornicolet ?

the full square is clickable

---

htdocs/view/layout/header.php

On peut merger
corrige le bug reçu sur balise.bugreport le 30 mars de la part d’alexandre

Retrait d'un mauvais lien

---

htdocs/asset/css/action/show.css
htdocs/helper/state.php
htdocs/view/binet/wave/show.php

Ajoute le montant utlisé dans la page de consultation d'une vague pour un binet ayant droit de voir le montant des subventions utilisé.

Amount used in subsidies

---

htdocs/controller/binet/member.php
htdocs/view/binet/request/review_form.php

redirect to new after member creation

---

htdocs/model/binet.php
htdocs/model/student.php

alphabetic order

---

htdocs/view/binet/budget/index.php
htdocs/view/binet/index.php
htdocs/view/binet/operation/index.php
htdocs/view/binet/request/index.php
htdocs/view/binet/wave/index.php

Redundant new links

---

htdocs/controller/binet/budget.php
htdocs/controller/binet/request.php
htdocs/form/budget.php
htdocs/form/request_entry.php
htdocs/view/binet/request/edit_form.php
htdocs/view/binet/request/new.php

New budget from request

---

htdocs/view/binet/budget/index.php

new budget even when non transferrable

---

htdocs/controller/binet/request.php
htdocs/form/budget.php
htdocs/form/request_entry.php

Request without budget
